reviews:
  sequence_diagrams: false
  poem: false
  #...
  path_instructions:
    - path: "**/*.js"
      instructions: |
        Review the JavaScript code against the Google JavaScript style guide and point out any mismatches
    - path: "app/Http/Controllers/**/*.php"
      instructions: |
        Review the following controllers. Ensure that:
        - The code adheres to best practices associated with PSR-12 and Laravel.
        - Descriptive method names are used to clearly convey the intent of each method.
        - комментарии к коду написаны на русском языке
        - к каждому классу написан комментарий, объясняющий, для чего нужен этот класс
        - у всех атрибутов классов (в частности, у ассоциативных массивов) с нестандартным форматом мы описываем этот формат
        - Мы не создаем избыточные геттеры/сеттеры атрибутов класса
        - Мы не создаем отдельные методы для получения/установки атрибута класса, если только для получения/установки не требуется дополнительных действий.
        - Мы используем транзакции БД только когда это необходимо
        - т.е. когда есть 2 или более запросов к базе данных, и невыполнение второго или последующих запросов нарушит консистентность данных.
          Например:
          правильно $this->update($data);
          но неправильно: DB::transaction(function() use ($data) {
            $this->update($data);
          });
        - Мы используем Dependency Injection в контроллерах. Когда роут включает в себя ID или другой ключ объекта, который пробрасывается в контроллер,
          в контроллере мы сразу получаем этот объект без дополнительного действия.
        - Для типовых CRUD-операций мы используем стандартые методы моделей. А не создаем дублирующие методы в моделях.
          При этом, если предполагается дополнительная нетиповая логика, то уже её мы выносим в модель (по принципу «тонких контроллеров», см ниже).
        - Значения, которые зависят от окружения, мы выносим в .env
        - Мы не используем .env-переменные в обход конфига, т.к. на продакшене используется кеширование конфига, и вызов .env-переменных напрямую не будет работать.
        - При передаче моделей из контроллера в шаблон мы описываем набор полей явно в контроллере.
          Чтобы лишние данные, которые не должны быть доступны в компоненте, не передавались; а также, чтобы при работе с frontend-частью можно было быстро увидеть набор полей.
          При этом Resource-классы для вывода в InertiaJS не используем (это инструмент для REST API).
        - Мы создаём «тонкие» контроллеры и «толстые» модели.
          Если действие связано с моделью, то выполнение основной логики мы переносим в модель, чтобы не захламлять контроллеры и при необходимости в будущем выполнять те же действия над данными из других контроллеров, задач, API и сервисов.
        - Мы выносим валидацию из контроллера в Form Request.
