reviews:
  #...
  path_instructions:
    - path: "**/*.js"
      instructions: |
        Review the JavaScript code against the Google JavaScript style guide and point out any mismatches
    - path: "app/Http/Controllers/**/*.php"
      instructions: |
        Review the following controllers. Ensure that:
        - The code adheres to best practices associated with PSR-12 and Laravel .
        - Descriptive method names are used to clearly convey the intent of each method.